name = "my-react-app"
type = "javascript"

# Define the Cloudflare account ID (find it in your Cloudflare dashboard)
account_id = "6be0d40c08dd64dddc478ccdc95d7dcd"

# Cloudflare Pages deployment settings
compatibility_date = "2025-02-22"

# Set the entry point for the Worker (use `dist` for Vite builds)
[site]
bucket = "./dist"
entry-point = "."

# Environment variables for the Worker
[env.production]
vars = { 
  VITE_INFOADDED_0: "$VITE_INFOADDED_0",
  VITE_CATEG_SECTOR: "$VITE_CATEG_SECTOR",
  VITE_ENABLE_BLOG: "$VITE_ENABLE_BLOG",
  VITE_GDPR: "$VITE_GDPR",
  VITE_URLFORM_DE: "$VITE_URLFORM_DE",
  VITE_URLFORM_FR: "$VITE_URLFORM_FR",
  VITE_URLFORM_EN: "$VITE_URLFORM_EN",
  VITE_URLFORM_ES: "$VITE_URLFORM_ES",
  VITE_LIMIT_LIST_ADMIN: "$VITE_LIMIT_LIST_ADMIN", 
  VITE_CHATGPT_URL: "$VITE_CHATGPT_URL",
  VITE_CHATGPT_KEY: "$VITE_CHATGPT_KEY",
  VITE_MAX_TOKENS_CHATGPT: "$VITE_MAX_TOKENS_CHATGPT",
  VITE_GEMINI_API_KEY: "$VITE_GEMINI_API_KEY",
  VITE_MAX_TOKENS_GEMINI: "$VITE_MAX_TOKENS_GEMINI",
  VITE_PERPLEXITY_API_KEY: "$VITE_PERPLEXITY_API_KEY",
  VITE_MAX_TOKENS_PERPLEXITY: "$VITE_MAX_TOKENS_PERPLEXITY",
  VITE_MODEL_PERPLEXITY: "$VITE_MODEL_PERPLEXITY",
  VITE_HUGGING_KEY: "$VITE_HUGGING_KEY",
  VITE_HUGGING_MODEL: "$VITE_HUGGING_MODEL",
  VITE_MAX_TOKENS_HUGGING: "$VITE_MAX_TOKENS_HUGGING",
  VITE_TYPE_AI: "$VITE_TYPE_AI",
  VITE_TYPE_COMPANY: "$VITE_TYPE_COMPANY",
  VITE_MSG_INFO_FR: "$VITE_MSG_INFO_FR",
  VITE_MSG_INFO_DE: "$VITE_MSG_INFO_DE",
  VITE_MSG_INFO_ES: "$VITE_MSG_INFO_ES",
  VITE_MSG_INFO_EN: "$VITE_MSG_INFO_EN",
  VITE_MSG_QUOTE_FR: "$VITE_MSG_QUOTE_FR",
  VITE_MSG_QUOTE_DE: "$VITE_MSG_QUOTE_DE",
  VITE_MSG_QUOTE_ES: "$VITE_MSG_QUOTE_ES",
  VITE_MSG_QUOTE_EN: "$VITE_MSG_QUOTE_EN",
  VITE_TYPE_CURRENCY: "$VITE_TYPE_CURRENCY",
  VITE_CSV_TABLE: "$VITE_CSV_TABLE",
  VITE_ID_CLIENT: "$VITE_ID_CLIENT",
  VITE_WHATSAPP: "$VITE_WHATSAPP",
  VITE_EMAIL: "$VITE_EMAIL",
  VITE_GOOGLEMAPS: "$VITE_GOOGLEMAPS",
  VITE_ADDRESS: "$VITE_ADDRESS",
  VITE_OPT_QUOTE: "$VITE_OPT_QUOTE",
  VITE_OPT_CITA: "$VITE_OPT_CITA",
  VITE_OPT_PRODUCT: "$VITE_OPT_PRODUCT",
  VITE_START_SLOT_AM: "$VITE_START_SLOT_AM",
  VITE_END_SLOT_AM: "$VITE_END_SLOT_AM",
  VITE_START_SLOT_PM: "$VITE_START_SLOT_PM",
  VITE_END_SLOT_PM: "$VITE_END_SLOT_PM",
  VITE_PUBLIC_HOLIDAYS_2025: "$VITE_PUBLIC_HOLIDAYS_2025",
  VITE_PUBLIC_HOLIDAYS_2026: "$VITE_PUBLIC_HOLIDAYS_2026",
  VITE_PUBLIC_HOLIDAYS_2027: "$VITE_PUBLIC_HOLIDAYS_2027",
  VITE_PUBLIC_HOLIDAYS_2028: "$VITE_PUBLIC_HOLIDAYS_2028",
  VITE_PUBLIC_HOLIDAYS_2029: "$VITE_PUBLIC_HOLIDAYS_2029",
  VITE_PUBLIC_HOLIDAYS_2030: "$VITE_PUBLIC_HOLIDAYS_2030",
  VITE_PUBLIC_HOLIDAYS_2031: "$VITE_PUBLIC_HOLIDAYS_2031",
  VITE_PUBLIC_HOLIDAYS_2032: "$VITE_PUBLIC_HOLIDAYS_2032",
  VITE_PUBLIC_HOLIDAYS_2033: "$VITE_PUBLIC_HOLIDAYS_2033",
  VITE_PUBLIC_HOLIDAYS_2034: "$VITE_PUBLIC_HOLIDAYS_2034",
  VITE_PUBLIC_HOLIDAYS_2035: "$VITE_PUBLIC_HOLIDAYS_2035",
  VITE_EMAIL_SERVICE_ID: "$VITE_EMAIL_SERVICE_ID",
  VITE_TEMPLATE_CITA: "$VITE_TEMPLATE_CITA",
  VITE_TEMPLATE_COMMENT: "$VITE_TEMPLATE_COMMENT",
  VITE_EMAIL_USER_ID: "$VITE_EMAIL_USER_ID",
  VITE_GRAPHQL_KEY: "$VITE_GRAPHQL_KEY",
  VITE_GRAPHQL_URL: "$VITE_GRAPHQL_URL",
  VITE_MAX_HEIGHT_LOGO: "$VITE_MAX_HEIGHT_LOGO",
  VITE_LOGO_URL: "$VITE_LOGO_URL",
  VITE_COMPANY_NAME: "$VITE_COMPANY_NAME",
  VITE_COMMENT_HISTORY: "$VITE_COMMENT_HISTORY",
  VITE_BACKENDLESS_APPID: "$VITE_BACKENDLESS_APPID",
  VITE_BACKENDLESS_REST: "$VITE_BACKENDLESS_REST"
};



# Secure secrets (set manually via `wrangler secret put`)
[secrets]
