name = "my-react-app"
type = "javascript"

# Define the Cloudflare account ID (find it in your Cloudflare dashboard)
account_id = "6be0d40c08dd64dddc478ccdc95d7dcd"

# Cloudflare Pages deployment settings
compatibility_date = "2025-02-22"

# Set the entry point for the Worker (use `dist` for Vite builds)
[site]
bucket = "./dist"
entry-point = "."

# Environment variables for the Worker
[env.production]
vars = { VITE_LANG = "$VITE_LANG", VITE_LIMIT_LIST_ADMIN = "$VITE_LIMIT_LIST_ADMIN" }


# Secure secrets (set manually via `wrangler secret put`)
[secrets]
